AWSTemplateFormatVersion: 2010-09-09
Resources:
  BlueoilNotebook:
    Type: 'AWS::SageMaker::NotebookInstance'
    Properties:
      InstanceType: "ml.t3.medium"
      NotebookInstanceName: "BlueoilNotebook"
      RoleArn:
        Fn::Join:
          - ':'
          - - 'arn:aws:iam:'
            - Ref: 'AWS::AccountId'
            - role/BlueoilSagemakerRole
      DefaultCodeRepository: 'https://github.com/LeapMind/bluegrass'
